Update powershell-scheduler.yml

diff --git a/.github/workflows/powershell-scheduler.yml b/.github/workflows/powershell-scheduler.yml
--- a/.github/workflows/powershell-scheduler.yml
+++ b/.github/workflows/powershell-scheduler.yml
@@ -14,6 +14,19 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v5
 
+      - name: Read Version
+        id: version
+        run: |
+          VERSION=$(cat ./powershell-scheduler/VERSION)
+
+          if [ -z "$VERSION" ]; then
+            echo "ERROR: VERSION file is empty."
+            exit 1
+          fi
+
+          echo "Building Powershell-Scheduler version $VERSION"
+          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v4
         with:
@@ -25,4 +38,6 @@ jobs:
         with:
           context: ./powershell-scheduler
           push: true
-          tags: ccridge/powershell-scheduler:latest
+          tags: |
+            ccridge/powershell-scheduler:${{ steps.version.outputs.version }}
+            ccridge/powershell-scheduler:latest
